name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action builds your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
branding:
  color: red
  icon: wifi
inputs:
  ssh_auth_sock:
    description: "Forward ssh agent into Docker container"
    default: ""
    required: false
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    default: ""
    required: false
  esp_idf_version:
    description: "Version of ESP-IDF docker image to use"
    default: "latest"
    required: false
  target:
    description: "ESP32 variant to build for"
    default: "esp32"
    required: false
  command:
    description: "Command to run inside the docker container (default: builds the project)"
    default: "idf.py build"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        export IDF_TARGET=$(echo "${{ inputs.target }}" | tr '[:upper:]' '[:lower:]' | tr -d '_-')
        export SSH_AUTH_SOCK=${{ inputs.ssh_auth_sock }}
        docker run -t \
        -e IDF_TARGET="${IDF_TARGET}" \
        -v $SSH_AUTH_SOCK:/ssh-agent \
        -e SSH_AUTH_SOCK=/ssh-agent \
        -u $UID \
        -e HOME=/tmp \
        -v ${GITHUB_WORKSPACE}:/project \
        -w /project espressif/idf:${{ inputs.esp_idf_version }} \
        /bin/bash -c '${{ inputs.command }}'
      shell: bash
